# Generated by Django 4.0.6 on 2023-01-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsnumberurlsmodel',
            name='category',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
