# Generated by Django 4.0.6 on 2023-01-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0002_productsnumberurlsmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsInCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('counter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductsNotSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('url', models.TextField()),
            ],
        ),
    ]
