# Generated by Django 4.0.6 on 2023-01-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0003_productsincategory_productsnotsaved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('wb_url', models.TextField()),
                ('first_page_products_url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Category page infos',
            },
        ),
        migrations.AlterModelOptions(
            name='productsincategory',
            options={'verbose_name_plural': 'Number of products in categories'},
        ),
        migrations.AlterModelOptions(
            name='productsnotsaved',
            options={'verbose_name_plural': 'Number of products urls not saved'},
        ),
    ]
