# Generated by Django 4.0.6 on 2023-01-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0005_productinfo_alter_categorypageinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wb_analytic_app.categorypageinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinfo',
            name='sold_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
