# Generated by Django 4.0.6 on 2023-01-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0006_productinfo_category_productinfo_sold_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesNotSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('wb_url', models.TextField()),
                ('first_page_products_url', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'All category page infos',
            },
        ),
    ]
