# Generated by Django 4.0.6 on 2023-01-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0007_categoriesnotsaved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesnotsaved',
            options={'verbose_name_plural': 'Categories not saved'},
        ),
        migrations.AddField(
            model_name='productinfo',
            name='save_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
