# Generated by Django 4.0.6 on 2023-01-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0008_alter_categoriesnotsaved_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountProductsNotSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wb_analytic_app.categorypageinfo')),
            ],
            options={
                'verbose_name_plural': 'Amount sold products not saved',
            },
        ),
    ]
