# Generated by Django 4.0.6 on 2023-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0009_amountproductsnotsaved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=128)),
                ('all_sold_products', models.IntegerField()),
                ('all_feedbacks', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ('category',), 'verbose_name_plural': 'Products info'},
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='save_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
