# Generated by Django 4.0.6 on 2023-02-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0010_analyticcategorymodel_alter_productinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wb_analytic_app.categorypageinfo'),
        ),
    ]
