# Generated by Django 4.0.6 on 2023-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0011_alter_productinfo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category_id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'All categories names',
            },
        ),
    ]
