# Generated by Django 4.0.6 on 2023-02-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0013_categorypageinfo_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'ordering': ('category_id',), 'verbose_name_plural': 'Products info'},
        ),
        migrations.RenameField(
            model_name='productinfo',
            old_name='category',
            new_name='category_id',
        ),
    ]
