# Generated by Django 4.0.6 on 2023-02-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0014_alter_productinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynamemodel',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categorynamemodel',
            name='shard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
