# Generated by Django 4.0.6 on 2023-02-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0015_categorynamemodel_query_categorynamemodel_shard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynamemodel',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorynamemodel',
            name='shard',
            field=models.TextField(blank=True, null=True),
        ),
    ]
