# Generated by Django 4.0.6 on 2023-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0016_alter_categorynamemodel_query_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypageinfo',
            name='wb_url',
        ),
        migrations.AddField(
            model_name='categorynamemodel',
            name='wb_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
