# Generated by Django 4.0.6 on 2023-02-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0017_remove_categorypageinfo_wb_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesnotsaved',
            name='wb_url',
        ),
        migrations.AddField(
            model_name='categoriesnotsaved',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wb_analytic_app.categorypageinfo'),
        ),
    ]
