# Generated by Django 4.0.6 on 2023-02-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0018_remove_categoriesnotsaved_wb_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wb_analytic_app.categorynamemodel'),
        ),
    ]
