# Generated by Django 4.0.6 on 2023-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_analytic_app', '0020_alter_productinfo_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='save_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
